// @flow
import {
    login,
    logout,
    signup,
    forgotPassword,
    forgotPasswordConfirm,
    firebaseLogin,
    firebaseSignup,
    firebaseLogout,
    firebaseFakeSingupForEmailVerification,
    firebaseSendEmailVerification,
    firebaseWatchEmailVerification,
    firebaseForgotPasswordSendPasswordResetEmail,
    firebaseDeleteUser,
    firebaseUpdateProfile,
    firebaseFakeUpdateProfile,
} from './auth';

export {
    login,
    logout,
    signup,
    forgotPassword,
    forgotPasswordConfirm,
    firebaseLogin,
    firebaseSignup,
    firebaseLogout,
    firebaseFakeSingupForEmailVerification,
    firebaseSendEmailVerification,
    firebaseWatchEmailVerification,
    firebaseForgotPasswordSendPasswordResetEmail,
    firebaseDeleteUser,
    firebaseUpdateProfile,
    firebaseFakeUpdateProfile,
};
