
const counselData = [
    {
        title: '신규등록률',
        stats: 72 + '%',
        value: 5.27 + '%',
        color: 'text-success',
        icon: 'up',
        border: 'primary',
    },
    {
        title: '재등록률',
        stats: 58 + '%',
        value: 5.27 + '%',
        color: 'text-danger',
        icon: 'down',
        border: 'danger',
    },
    {
        title: '신규등록',
        stats: 300 + '명',
        value: 29 + '명',
        color: 'text-success',
        icon: 'up',
    },
    {
        title: '재등록',
        stats: 22 + '명',
        value: 5 + '명',
        color: 'text-danger',
        icon: 'down',
    },
    {
        title: '상담유입',
        stats: 554 + '명',
        value: 52 + '명',
        color: 'text-success',
        icon: 'up',
    },
    {
        title: '재등록대상',
        stats: 50 + '명',
        value: 5.27 + '%',
        color: 'text-success',
        icon: 'up',
    }
]

const counselorData = [
    {
        id: 1,
        name: '주용환',
        newConsult: 84,
        newRegister: 56,
        newRate: 72,
        reTarget: 3,
        reRegister: 23,
        leave: 120,
        sales: 10000000,
    },
    {
        id: 2,
        name: '김유환',
        newConsult: 84,
        newRegister: 56,
        newRate: 72,
        reTarget: 3,
        reRegister: 23,
        leave: 120,
        sales: 10000000,
    },
    {
        id: 3,
        name: '이수민',
        newConsult: 84,
        newRegister: 56,
        newRate: 72,
        reTarget: 3,
        reRegister: 23,
        leave: 120,
        sales: 10000000,
    },
    {
        id: 4,
        name: '심하은',
        newConsult: 84,
        newRegister: 56,
        newRate: 72,
        reTarget: 3,
        reRegister: 23,
        leave: 120,
        sales: 10000000,
    },
    {
        id: 5,
        name: '유승훈',
        newConsult: 84,
        newRegister: 56,
        newRate: 72,
        reTarget: 3,
        reRegister: 23,
        leave: 120,
        sales: 10000000,
    },
];

export { counselData, counselorData };